New file added
jayeshsony/MySQL pull request #1
Opened 2024-04-29 07:46 UTC by jayeshsony

2024-04-29 09:38 UTC, KrushaliTalaviya requested changes

2024-04-29 09:38 UTC, KrushaliTalaviya commented on practical.sql
> +  CONSTRAINT `employee_salary_fk` FOREIGN KEY (`fk_employee_id`) REFERENCES `employee` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
Please Remove  ON DELETE CASCADE ON UPDATE CASCADE from all

2024-04-29 09:38 UTC, KrushaliTalaviya commented on practical.sql
> +
Where is the Update Query?

2024-04-29 09:38 UTC, KrushaliTalaviya commented on practical.sql
> +SELECT concat(first_name, ' ', last_name) AS 'Employee Name'
Format This query
As well as also change the name of the alias, We can use name like employee_name

2024-04-29 10:11 UTC, jayeshsony commented
Added  comments and formatted queries.

2024-04-29 10:16 UTC, jayeshsony commented
Added details and formatted the queries.

2024-04-29 10:27 UTC, jayeshsony commented
Added comments and formatted the queries.

2024-04-30 13:32 UTC, KrushaliTalaviya approved these changes

2024-04-30 13:34 UTC, merged